// Tests for parseCaddyfileSite in src/routes/system.js.
//
// This parser is what the TLS tab reads to find the Hub's hostname, and what
// the renew-cert endpoint uses to decide which host to re-issue for. It broke
// in production: scripts/install-hub-caddy.ps1 writes the site block as
// `${Hostname}$(if ($ListenPort -ne 443) { ":$ListenPort" }) {`, so any hub
// installed with -ListenPort (needed where IIS / the Sage 300 Web API already
// hold :443 via an HTTP.sys reservation) produced a line the old regex could
// not match. Hostname came back null, which greyed out the Renew cert button
// and made the cert section claim "No cert found" without ever looking —
// on the head-office hub, whose cert then expired and took every site→hub
// push down with it.
//
// The first case below is the exact line from that hub. Keep it.
import { describe, it, expect } from 'vitest';
import { parseCaddyfileSite } from '../src/routes/system.js';

// Mirrors the template in scripts/install-hub-caddy.ps1.
const caddyfile = (siteLine) => `# Cardoso Hub Caddy config — generated by scripts/install-hub-caddy.ps1

{
    auto_https disable_redirects
}

${siteLine}
    tls C:\\Caddy\\host.crt C:\\Caddy\\host.key

    reverse_proxy http://127.0.0.1:3001 {
        header_up X-Real-IP {remote_host}
    }

    encode gzip
}
`;

describe('parseCaddyfileSite', () => {
  it('reads a hostname with a non-default listen port (the head-office hub)', () => {
    const parsed = parseCaddyfileSite(
      caddyfile('cardoso-headoffice.buffalo-salak.ts.net:8443 {')
    );
    expect(parsed.hostname).toBe('cardoso-headoffice.buffalo-salak.ts.net');
    expect(parsed.listen_port).toBe(8443);
    expect(parsed.backend_port).toBe(3001);
  });

  it('reads a hostname on the default port, where the installer omits :443', () => {
    const parsed = parseCaddyfileSite(
      caddyfile('cardoso-headoffice.buffalo-salak.ts.net {')
    );
    expect(parsed.hostname).toBe('cardoso-headoffice.buffalo-salak.ts.net');
    expect(parsed.listen_port).toBe(443);
  });

  it('tolerates an explicit scheme and leading whitespace', () => {
    expect(parseCaddyfileSite(caddyfile('https://hub.example-tailnet.ts.net:8443 {')).hostname)
      .toBe('hub.example-tailnet.ts.net');
    expect(parseCaddyfileSite(caddyfile('  hub.example-tailnet.ts.net:8443 {')).hostname)
      .toBe('hub.example-tailnet.ts.net');
  });

  it('does not match the global options block that opens the file', () => {
    // A bare `{` on its own line precedes the site block; the parser must
    // skip it rather than returning a null hostname for the whole file.
    const parsed = parseCaddyfileSite(caddyfile('hub.example-tailnet.ts.net:8443 {'));
    expect(parsed.hostname).not.toBeNull();
  });

  it('returns nulls for a Caddyfile with no .ts.net site block', () => {
    const parsed = parseCaddyfileSite('localhost:8080 {\n    respond "hi"\n}\n');
    expect(parsed.hostname).toBeNull();
    expect(parsed.listen_port).toBeNull();
  });

  it('keeps hostname and listen_port independent of the backend port', () => {
    const parsed = parseCaddyfileSite(
      caddyfile('cardoso-headoffice.buffalo-salak.ts.net:8443 {')
    );
    // 8443 is what Caddy listens on; 3001 is the Node backend behind it.
    expect(parsed.listen_port).not.toBe(parsed.backend_port);
  });
});
