// Auto-generated by scripts/_extract-migrations.mjs.
// Imports every per-version migration file and exports them sorted
// by version number. Add a new migration by creating vNNN_name.js
// in this directory and adding it to the list below.

import m1 from './v001_initial_schema_columns.js';
import m2 from './v002_invoice_receipt_numbered_columns.js';
import m3 from './v003_flag_source_and_terms.js';
import m4 from './v004_query_mode_and_inventory_columns.js';
import m5 from './v005_field_mappings_per_table_format.js';
import m6 from './v006_user_permissions.js';
import m7 from './v007_invoice_receipt_json_columns.js';
import m8 from './v008_hub_schema_columns.js';
import m9 from './v009_record_snapshots_table.js';
import m10 from './v010_hub_sites_token.js';
import m11 from './v011_hub_inventory_value_column.js';
import m12 from './v012_inventoryrecord_missing_columns.js';
import m13 from './v013_hub_sites_token_force.js';
import m14 from './v014_force_add_missing_columns.js';
import m15 from './v015_datarecord_complete_schema.js';
import m16 from './v016_hub_user_sites_table.js';
import m17 from './v017_feature_permissions_balances_inventory.js';
import m18 from './v018_speedtest_tables.js';
import m19 from './v019_ensure_speedtest_tables.js';
import m20 from './v020_hub_site_ping_table.js';
import m21 from './v021_ensure_hub_user_sites_table.js';
import m22 from './v022_collections_pipeline_table.js';
import m23 from './v023_hub_audit_log_table.js';
import m24 from './v024_hub_backup_integrity_table.js';
import m25 from './v025_feature_permissions_sidebar_expansion.js';
import m26 from './v026_hub_records_flag_created_by.js';
import m27 from './v027_network_devices_tables.js';
import m28 from './v028_feature_permission_network_devices.js';
import m29 from './v029_credit_logic_centralisation.js';
import m30 from './v030_drop_network_device_bandwidth_tables.js';
import m31 from './v031_ntopng_hub_settings.js';
import m32 from './v032_databaseconnection_use_encryption.js';
import m33 from './v033_perf_indexes_hub_inventory_and_records.js';
import m34 from './v034_perf_index_autoflagrule_active_priority.js';
import m35 from './v035_inventory_sales_rep_column.js';
import m36 from './v036_datarecord_sales_rep_and_backfill.js';
import m37 from './v037_hub_user_allowed_sites.js';
import m38 from './v038_remove_sales_rep_from_inventory_tables.js';
import m39 from './v039_datarecord_account_type_column.js';
import m40 from './v040_backfill_sales_rep_and_account_type_from_data_json.js';
import m41 from './v041_create_flag_snapshots_table.js';
import m42 from './v042_dedupe_datarecords_and_trim_source_ids.js';
import m43 from './v043_drop_speedtest_tables.js';
import m44 from './v044_bat_sage_week_cache.js';
import m45 from './v045_bat_reconciliation_perf_indexes.js';
import m46 from './v046_databaseconnection_is_bat_only.js';
import m47 from './v047_datarecord_outstanding_balance_num.js';
import m48 from './v048_hub_bat_summary.js';
import m49 from './v049_reconciliation_permissions.js';
import m50 from './v050_perf_indexes_audit_and_bat_extractions.js';
import m51 from './v051_normalise_unpaid_invoice_numbers.js';
import m52 from './v052_connection_role.js';
import m53 from './v053_error_log.js';
import m54 from './v054_fix_hub_records_balance_num_triggers.js';
import m55 from './v055_admin_module_visibility.js';
import m56 from './v056_fix_hub_records_unpaid_invoice_numbers_triggers.js';
import m57 from './v057_hub_bat_summary_missing_weeks.js';
import m58 from './v058_hub_bat_summary_per_week_detail.js';
import m59 from './v059_bat_year_scoped_indexes.js';
import m60 from './v060_job_runs.js';
import m61 from './v061_alerts.js';
import m62 from './v062_hub_sites_accpac_freshness.js';
import m63 from './v063_hub_sites_orphan_tombstone.js';
import m64 from './v064_datarecord_customer_name_lower_index.js';
import m65 from './v065_auditlog_drop_resource_type_check.js';
import m66 from './v066_drop_defunct_record_snapshots.js';
import m67 from './v067_drop_defunct_hub_audit_log.js';
import m68 from './v068_bat_reconciliations_archive_path.js';
import m69 from './v069_jti_export_permission_and_settings.js';
import m70 from './v070_jti_archive_table.js';
import m71 from './v071_hub_jti_archive_table.js';
import m72 from './v072_bat_overview_orders_for_pod_coverage.js';
import m73 from './v073_bat_overview_orders_amount_nullable.js';
import m74 from './v074_inventory_sales_cache.js';
import m75 from './v075_stock_receipt_expiry.js';
import m76 from './v076_split_inventory_movement_permission.js';
import m77 from './v077_add_price_list_permission.js';
import m78 from './v078_depot_profile.js';
import m79 from './v079_price_list_exclusions.js';
import m80 from './v080_collections_worklists_v1.js';
import m81 from './v081_commission_settings.js';
import m82 from './v082_commission_vat_rate.js';
import m83 from './v083_commission_archive.js';
import m84 from './v084_hub_commission_archive.js';
import m85 from './v085_commission_sql_overrides.js';
import m86 from './v086_admin_can_access_backfill.js';
import m87 from './v087_creditors_module.js';
import m88 from './v088_commission_unpaid_override.js';
import m89 from './v089_commission_unpaid_snapshot.js';
import m90 from './v090_insight_rules.js';
import m91 from './v091_commission_vat_rate_15_default.js';
import m92 from './v092_debtor_ar_module.js';
import m93 from './v093_debtor_reporting_account.js';
import m94 from './v094_hub_ar_document_summary.js';
import m95 from './v095_monthly_reports_permission.js';
import m96 from './v096_sage_query_override.js';
import m97 from './v097_inventory_sales_cache_description.js';
import m98 from './v098_hub_inventory_sales_aggregates.js';
import m99 from './v099_inventory_sales_rollup_cache.js';
import m100 from './v100_hub_debtor_ar_sync.js';
import m101 from './v101_creditor_unposted_payments.js';
import m102 from './v102_creditor_unposted_invoices.js';
import m103 from './v103_creditor_capture_meta.js';
import m104 from './v104_inventory_movement_history.js';
import m105 from './v105_hub_bat_exceptions.js';
import m106 from './v106_item_vendor.js';

const migrations = [
  m1,
  m2,
  m3,
  m4,
  m5,
  m6,
  m7,
  m8,
  m9,
  m10,
  m11,
  m12,
  m13,
  m14,
  m15,
  m16,
  m17,
  m18,
  m19,
  m20,
  m21,
  m22,
  m23,
  m24,
  m25,
  m26,
  m27,
  m28,
  m29,
  m30,
  m31,
  m32,
  m33,
  m34,
  m35,
  m36,
  m37,
  m38,
  m39,
  m40,
  m41,
  m42,
  m43,
  m44,
  m45,
  m46,
  m47,
  m48,
  m49,
  m50,
  m51,
  m52,
  m53,
  m54,
  m55,
  m56,
  m57,
  m58,
  m59,
  m60,
  m61,
  m62,
  m63,
  m64,
  m65,
  m66,
  m67,
  m68,
  m69,
  m70,
  m71,
  m72,
  m73,
  m74,
  m75,
  m76,
  m77,
  m78,
  m79,
  m80,
  m81,
  m82,
  m83,
  m84,
  m85,
  m86,
  m87,
  m88,
  m89,
  m90,
  m91,
  m92,
  m93,
  m94,
  m95,
  m96,
  m97,
  m98,
  m99,
  m100,
  m101,
  m102,
  m103,
  m104,
  m105,
  m106,
];

migrations.sort((a, b) => a.version - b.version);

export default migrations;
