import { ensureColumn, ensureTable } from './_helpers.js';

export default {
  // Site-side monthly commission archive — mirrors the jti_archive
  // pattern (v70). Generated by the scheduled job on the 24th of each
  // month covering the 24th-prev-month → 23rd-current-month window.
  // Operator-initiated runs (manual) also land here so the two coexist
  // side-by-side per period.
  //
  // Hub push lifecycle: pending → pushed | failed | skipped_no_hub.
  version: 83,
  name: 'commission_archive_table',
  up(db) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS commission_archive (
        id INTEGER PRIMARY KEY AUTOINCREMENT,

        -- The commission month this archive belongs to. By convention
        -- the period covers (period_month-1).24 → period_month.23, but
        -- the from/to fields below carry the exact dates used so future
        -- changes to the cycle don't break older rows.
        period_year   INTEGER NOT NULL,
        period_month  INTEGER NOT NULL CHECK (period_month BETWEEN 1 AND 12),
        period_from   TEXT NOT NULL,
        period_to     TEXT NOT NULL,

        -- Provenance
        generated_at  TEXT NOT NULL DEFAULT (datetime('now')),
        generated_by  TEXT,
        source        TEXT NOT NULL CHECK (source IN ('scheduled', 'manual')),

        -- File on disk — PDF is the canonical form sent to the hub
        filename      TEXT NOT NULL,
        file_path     TEXT NOT NULL,
        byte_size     INTEGER NOT NULL,
        sha256        TEXT NOT NULL,

        -- Snapshot of the rendered report payload (JSON) so the hub
        -- can regenerate views without re-querying Sage. Also used by
        -- the local UI's "view archive" detail panel.
        report_json   TEXT NOT NULL,

        -- Stamped at write time so a future depot rename doesn't make
        -- old archives ambiguous about which site they came from.
        site_label    TEXT,

        -- Hub push state machine (same as jti_archive)
        hub_push_status   TEXT NOT NULL DEFAULT 'pending'
          CHECK (hub_push_status IN ('pending', 'pushed', 'failed', 'skipped_no_hub')),
        hub_push_at       TEXT,
        hub_push_error    TEXT,
        hub_push_attempts INTEGER NOT NULL DEFAULT 0
      )
    `);

    // Read pattern: list archives latest first per period — drives the
    // archive panel on the Sales Commission page.
    db.exec(`
      CREATE INDEX IF NOT EXISTS idx_commission_archive_period
      ON commission_archive(period_year DESC, period_month DESC, generated_at DESC)
    `);

    // Retry job scans pending/failed rows hourly.
    db.exec(`
      CREATE INDEX IF NOT EXISTS idx_commission_archive_hub_push
      ON commission_archive(hub_push_status)
    `);

    // Idempotency guard for scheduled runs — at most one scheduled
    // archive per (period_year, period_month). Manual runs are not
    // unique-constrained so an operator can re-run them ad hoc.
    db.exec(`
      CREATE UNIQUE INDEX IF NOT EXISTS idx_commission_archive_scheduled_unique
      ON commission_archive(period_year, period_month)
      WHERE source = 'scheduled'
    `);
  },
};
