-- AUTOGENERATED by scripts/dump-schema-snapshot.mjs.
-- Do not edit by hand — re-run the script after a schema change.
-- Source of truth: src/db/migrations.js (latest version: 80)
-- Generated: 2026-05-28T16:36:38.348Z

-- ── alerts ──
CREATE TABLE alerts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            rule_name TEXT NOT NULL,
            severity TEXT NOT NULL CHECK (severity IN ('critical','warning','info')),
            message TEXT NOT NULL,
            context TEXT,
            dedup_key TEXT NOT NULL,
            fired_at TEXT NOT NULL,
            resolved_at TEXT,
            resolved_by TEXT
          );
CREATE INDEX idx_alerts_active_dedup
            ON alerts(dedup_key) WHERE resolved_at IS NULL;
CREATE INDEX idx_alerts_fired ON alerts(fired_at DESC);

-- ── auditlog ──
CREATE TABLE "auditlog" (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            action_type TEXT NOT NULL,
            user_email TEXT NOT NULL,
            user_name TEXT,
            resource_type TEXT,
            resource_id TEXT,
            resource_name TEXT,
            action_details TEXT,
            changes TEXT,
            ip_address TEXT,
            status TEXT CHECK(status IN ('success', 'failure')) NOT NULL,
            created_date TEXT DEFAULT CURRENT_TIMESTAMP
          );
CREATE INDEX idx_auditlog_created_date
            ON auditlog(created_date);
CREATE INDEX idx_auditlog_resource
            ON auditlog(resource_type, resource_id, created_date DESC);

-- ── autoflagrule ──
CREATE TABLE autoflagrule (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      rule_name TEXT NOT NULL,
      conditions TEXT,
      logic TEXT CHECK(logic IN ('AND', 'OR')),
      flag_color TEXT CHECK(flag_color IN ('red', 'green', 'orange')) NOT NULL,
      is_active INTEGER DEFAULT 1,
      priority INTEGER,
      created_by TEXT,
      created_date TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_date TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE INDEX idx_autoflagrule_active_priority
          ON autoflagrule (is_active, priority DESC);

-- ── bat_cardoso_invoices ──
CREATE TABLE bat_cardoso_invoices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      reconciliation_id INTEGER REFERENCES bat_reconciliations(id) ON DELETE CASCADE,
      invoice_number TEXT NOT NULL,
      amount REAL,
      upload_filename TEXT,
      raw_data TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    , price_diff REAL, discount REAL, del_fee REAL, c_overwritten INTEGER DEFAULT 0);
CREATE INDEX idx_bat_cardoso_inv_num ON bat_cardoso_invoices(invoice_number);
CREATE INDEX idx_bat_cardoso_inv_overwritten
          ON bat_cardoso_invoices(c_overwritten);
CREATE INDEX idx_bat_cardoso_inv_recon ON bat_cardoso_invoices(reconciliation_id);

-- ── bat_invoice_extractions ──
CREATE TABLE bat_invoice_extractions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      reconciliation_id INTEGER REFERENCES bat_reconciliations(id) ON DELETE CASCADE,
      pdf_url TEXT NOT NULL,
      order_number TEXT,
      branch_name TEXT,
      store_name TEXT,
      week TEXT,
      order_day TEXT,
      delivery_day TEXT,
      lead_time INTEGER,
      delivery_date TEXT,
      pod_uploaded_date TEXT,
      validate TEXT,
      extracted_invoice TEXT,
      extraction_status TEXT DEFAULT 'pending',
      extraction_attempts INTEGER DEFAULT 0,
      sage_match_document TEXT,
      sage_match_amount REAL,
      match_status TEXT DEFAULT 'pending',
      preview_path TEXT,
      order_amount REAL,
      is_exception INTEGER DEFAULT 0,
      target_days INTEGER,
      compliance_status TEXT,
      exception_reason TEXT,
      created_at TEXT DEFAULT (datetime('now')), supplier_discount REAL, supplier_del_fee REAL, supplier_pricing REAL, extraction_error TEXT, manual_override INTEGER DEFAULT 0,
      UNIQUE(reconciliation_id, pdf_url)
    );
CREATE INDEX idx_bat_extractions_exception
              ON bat_invoice_extractions(is_exception)
              WHERE is_exception = 1;
CREATE INDEX idx_bat_extractions_invoice
          ON bat_invoice_extractions(extracted_invoice)
          WHERE extracted_invoice IS NOT NULL;
CREATE INDEX idx_bat_extractions_recon ON bat_invoice_extractions(reconciliation_id);
CREATE INDEX idx_bat_extractions_recon_status
                 ON bat_invoice_extractions(reconciliation_id, extraction_status, id);
CREATE INDEX idx_bat_extractions_status ON bat_invoice_extractions(extraction_status);

-- ── bat_overview_orders ──
CREATE TABLE "bat_overview_orders" (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            reconciliation_id INTEGER NOT NULL REFERENCES bat_reconciliations(id) ON DELETE CASCADE,
            order_number TEXT NOT NULL,
            is_exception INTEGER NOT NULL DEFAULT 0 CHECK (is_exception IN (0, 1)),
            order_amount REAL,
            supplier_discount REAL DEFAULT 0,
            supplier_delivery REAL DEFAULT 0,
            supplier_pricing  REAL DEFAULT 0,
            created_at TEXT DEFAULT (datetime('now')),
            UNIQUE(reconciliation_id, order_number)
          );
CREATE INDEX idx_bat_overview_orders_recon_exc
            ON bat_overview_orders(reconciliation_id, is_exception);

-- ── bat_reconciliations ──
CREATE TABLE bat_reconciliations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      week_number INTEGER NOT NULL,
      year INTEGER NOT NULL,
      upload_filename TEXT,
      supplier_discount REAL,
      supplier_delivery REAL,
      supplier_pricing REAL,
      supplier_discount_vat REAL,
      supplier_delivery_vat REAL,
      supplier_pricing_vat REAL,
      supplier_total REAL,
      sage_discount REAL,
      sage_delivery REAL,
      sage_pricing REAL,
      sage_total REAL,
      status TEXT DEFAULT 'pending',
      created_by INTEGER,
      created_at TEXT DEFAULT (datetime('now')), last_error TEXT, last_error_at TEXT, sage_error TEXT, marked_zero INTEGER DEFAULT 0, marked_zero_by TEXT, marked_zero_at TEXT, marked_zero_note TEXT, archive_path TEXT,
      UNIQUE(week_number, year)
    );
CREATE INDEX idx_bat_recon_week ON bat_reconciliations(week_number, year);
CREATE INDEX idx_bat_recon_year_week ON bat_reconciliations(year, week_number);

-- ── bat_sage_cache_meta ──
CREATE TABLE bat_sage_cache_meta (
            key TEXT PRIMARY KEY,
            value TEXT,
            updated_at TEXT
          );

-- ── bat_sage_credit_notes ──
CREATE TABLE bat_sage_credit_notes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      reconciliation_id INTEGER REFERENCES bat_reconciliations(id) ON DELETE CASCADE,
      batch_number INTEGER,
      batch_description TEXT,
      batch_status TEXT,
      vendor_number TEXT,
      document_number TEXT,
      document_date TEXT,
      line_description TEXT,
      week_number INTEGER,
      fee_type TEXT,
      line_amount REAL,
      created_at TEXT DEFAULT (datetime('now'))
    );
CREATE INDEX idx_bat_sage_cn_recon ON bat_sage_credit_notes(reconciliation_id);

-- ── bat_sage_week_cache ──
CREATE TABLE bat_sage_week_cache (
            year INTEGER NOT NULL,
            week_number INTEGER NOT NULL,
            delivery REAL DEFAULT 0,
            discount REAL DEFAULT 0,
            pricing REAL DEFAULT 0,
            total REAL DEFAULT 0,
            batch_count INTEGER DEFAULT 0,
            refreshed_at TEXT,
            PRIMARY KEY (year, week_number)
          );
CREATE INDEX idx_bat_sage_cache_year_week ON bat_sage_week_cache(year, week_number);

-- ── bat_settings ──
CREATE TABLE bat_settings (
      key TEXT PRIMARY KEY,
      value TEXT,
      updated_at TEXT DEFAULT (datetime('now'))
    );

-- ── collection_activity ──
CREATE TABLE collection_activity (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_id TEXT NOT NULL,
            assignment_id INTEGER REFERENCES collection_assignment(id) ON DELETE SET NULL,
            user_id INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
            kind TEXT NOT NULL,
            at TEXT DEFAULT (datetime('now')),
            amount REAL,
            promise_date TEXT,
            previous_balance REAL,
            new_balance REAL,
            notes TEXT,
            source TEXT DEFAULT 'manual'
          );
CREATE INDEX idx_collection_activity_assignment
            ON collection_activity(assignment_id, at DESC);
CREATE INDEX idx_collection_activity_customer
            ON collection_activity(customer_id, at DESC);
CREATE INDEX idx_collection_activity_kind
            ON collection_activity(kind, at DESC);

-- ── collection_assignment ──
CREATE TABLE collection_assignment (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            worklist_id INTEGER NOT NULL REFERENCES collection_worklist(id) ON DELETE CASCADE,
            customer_id TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            assigned_at TEXT DEFAULT (datetime('now')),
            assigned_by_user_id INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
            closed_at TEXT,
            closed_reason TEXT,
            next_followup_date TEXT,
            opening_balance REAL,
            -- Last-known balance from sync — used by the auto-detect hook
            -- to spot a balance drop without scanning the whole datarecord.
            last_known_balance REAL,
            last_sync_at TEXT,
            UNIQUE(worklist_id, customer_id)
          );
CREATE INDEX idx_collection_assignment_customer
            ON collection_assignment(customer_id);
CREATE INDEX idx_collection_assignment_followup
            ON collection_assignment(next_followup_date)
            WHERE status = 'active' AND next_followup_date IS NOT NULL;
CREATE INDEX idx_collection_assignment_worklist_status
            ON collection_assignment(worklist_id, status);

-- ── collection_worklist ──
CREATE TABLE collection_worklist (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            owner_user_id INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
            description TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            created_by_user_id INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
            archived_at TEXT
          );
CREATE INDEX idx_collection_worklist_owner
            ON collection_worklist(owner_user_id) WHERE archived_at IS NULL;

-- ── collections ──
CREATE TABLE collections (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_id TEXT NOT NULL UNIQUE,
            status TEXT DEFAULT 'pending',
            contacted_at TEXT,
            notes TEXT,
            updated_at TEXT DEFAULT (datetime('now'))
          );
CREATE INDEX idx_collections_customer_id ON collections(customer_id);
CREATE INDEX idx_collections_status ON collections(status);

-- ── connection_role ──
CREATE TABLE connection_role (
            role TEXT PRIMARY KEY,
            connection_id INTEGER NOT NULL REFERENCES databaseconnection(id) ON DELETE CASCADE,
            updated_at TEXT DEFAULT (datetime('now'))
          );

-- ── credit_logic_state ──
CREATE TABLE credit_logic_state (
            scope TEXT PRIMARY KEY,
            logic_version INTEGER,
            payload_json TEXT,
            schema_version INTEGER NOT NULL DEFAULT 1,
            published_at TEXT,
            last_synced_at TEXT,
            sync_status TEXT DEFAULT 'never_synced',
            last_error TEXT,
            source TEXT DEFAULT 'default',
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
          );

-- ── credit_logic_versions ──
CREATE TABLE credit_logic_versions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            version INTEGER NOT NULL UNIQUE,
            schema_version INTEGER NOT NULL DEFAULT 1,
            config_json TEXT NOT NULL,
            notes TEXT,
            created_by TEXT,
            is_active INTEGER DEFAULT 0,
            published_at TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
          );
CREATE INDEX idx_credit_logic_versions_active ON credit_logic_versions(is_active, version DESC);

-- ── customfieldconfig ──
CREATE TABLE customfieldconfig (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        field_key TEXT NOT NULL UNIQUE,
        label TEXT NOT NULL,
        field_type TEXT CHECK(field_type IN ('text', 'select', 'number', 'date')) NOT NULL,
        options TEXT,
        is_active INTEGER DEFAULT 1,
        created_by TEXT,
        created_date TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_date TEXT DEFAULT CURRENT_TIMESTAMP
      );

-- ── databaseconnection ──
CREATE TABLE databaseconnection (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      host TEXT NOT NULL,
      port INTEGER NOT NULL,
      database_name TEXT NOT NULL,
      username TEXT NOT NULL,
      encrypted_password TEXT,
      use_encryption INTEGER NOT NULL DEFAULT 0,
      table_configs TEXT,
      join_configuration TEXT,
      field_mappings TEXT,
      status TEXT CHECK(status IN ('active', 'inactive', 'error', 'testing')) DEFAULT 'inactive',
      last_sync TEXT,
      last_error TEXT,
      record_count INTEGER DEFAULT 0,
      created_by TEXT,
      created_date TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_date TEXT DEFAULT CURRENT_TIMESTAMP
    , sync_query TEXT, query_index_field TEXT, query_field_mappings TEXT, record_type TEXT DEFAULT 'customer', sync_interval_hours INTEGER, is_bat_only INTEGER DEFAULT 0);
CREATE INDEX idx_databaseconnection_status
    ON databaseconnection (status);

-- ── datarecord ──
CREATE TABLE datarecord (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      created_date TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_date TEXT DEFAULT CURRENT_TIMESTAMP,
      created_by TEXT,
      customer_number TEXT,
      customer_name TEXT,
      age_analysis TEXT,
      age_current TEXT,
      age_7_days TEXT,
      age_14_days TEXT,
      age_21_days TEXT,
      outstanding_balance TEXT,
      source_id TEXT,
      source_table TEXT,
      data TEXT,
      custom_field_1 TEXT,
      custom_field_2 TEXT,
      custom_field_3 TEXT,
      local_fields TEXT DEFAULT '{}',
      last_unpaid_invoice_1 TEXT,
      last_unpaid_invoice_1_amount TEXT,
      last_unpaid_invoice_2 TEXT,
      last_unpaid_invoice_2_amount TEXT,
      last_unpaid_invoice_3 TEXT,
      last_unpaid_invoice_3_amount TEXT,
      unpaid_invoices TEXT,
      receipts TEXT,
      flag_color TEXT CHECK(flag_color IN ('none', 'red', 'green', 'orange')) DEFAULT 'none',
      flag_reason TEXT,
      flag_created_by TEXT,
      flag_source TEXT DEFAULT NULL,
      note TEXT,
      synced_at TEXT,
      last_checked TEXT,
      terms TEXT,
      sales_rep TEXT,
      account_type TEXT,
      auto_flagged INTEGER DEFAULT 0
    , last_unpaid_invoice_1_date TEXT, last_receipt_1 TEXT, last_receipt_1_amount TEXT, last_receipt_1_date TEXT, last_unpaid_invoice_2_date TEXT, last_receipt_2 TEXT, last_receipt_2_amount TEXT, last_receipt_2_date TEXT, last_unpaid_invoice_3_date TEXT, last_receipt_3 TEXT, last_receipt_3_amount TEXT, last_receipt_3_date TEXT, last_unpaid_invoice_4 TEXT, last_unpaid_invoice_4_amount TEXT, last_unpaid_invoice_4_date TEXT, last_receipt_4 TEXT, last_receipt_4_amount TEXT, last_receipt_4_date TEXT, last_unpaid_invoice_5 TEXT, last_unpaid_invoice_5_amount TEXT, last_unpaid_invoice_5_date TEXT, last_receipt_5 TEXT, last_receipt_5_amount TEXT, last_receipt_5_date TEXT, outstanding_balance_num REAL, unpaid_invoice_numbers TEXT);
CREATE INDEX idx_datarecord_auto_flagged ON datarecord (auto_flagged);
CREATE INDEX idx_datarecord_balance_num ON datarecord(outstanding_balance_num);
CREATE INDEX idx_datarecord_customer_name_lower
            ON datarecord(lower(customer_name));
CREATE INDEX idx_datarecord_customer_number
    ON datarecord (customer_number);
CREATE INDEX idx_datarecord_flag_color
    ON datarecord (flag_color);
CREATE INDEX idx_datarecord_flag_source ON datarecord (flag_source);
CREATE INDEX idx_datarecord_outstanding_balance ON datarecord (outstanding_balance);
CREATE INDEX idx_datarecord_sales_rep ON datarecord (sales_rep) WHERE sales_rep IS NOT NULL AND sales_rep != '';
CREATE INDEX idx_datarecord_source_lookup
    ON datarecord (source_table, source_id);
CREATE UNIQUE INDEX idx_datarecord_source_unique ON datarecord (source_table, source_id) WHERE source_id IS NOT NULL AND source_id != '';
CREATE INDEX idx_datarecord_terms ON datarecord (terms);
CREATE INDEX idx_datarecord_unpaid_invoice_numbers
                 ON datarecord(unpaid_invoice_numbers);
CREATE INDEX idx_datarecord_updated_date
    ON datarecord (updated_date);
CREATE TRIGGER datarecord_unpaid_invoice_numbers_ai
          AFTER INSERT ON datarecord
          WHEN NEW.unpaid_invoices IS NOT NULL
          BEGIN
            UPDATE datarecord
               SET unpaid_invoice_numbers = COALESCE((
                 SELECT GROUP_CONCAT(UPPER(json_extract(value, '$.number')), ' ')
                   FROM json_each(NEW.unpaid_invoices)
                  WHERE json_extract(value, '$.number') IS NOT NULL
               ), '')
             WHERE id = NEW.id;
          END;
CREATE TRIGGER datarecord_unpaid_invoice_numbers_au
          AFTER UPDATE OF unpaid_invoices ON datarecord
          
          BEGIN
            UPDATE datarecord
               SET unpaid_invoice_numbers = COALESCE((
                 SELECT GROUP_CONCAT(UPPER(json_extract(value, '$.number')), ' ')
                   FROM json_each(NEW.unpaid_invoices)
                  WHERE json_extract(value, '$.number') IS NOT NULL
               ), '')
             WHERE id = NEW.id;
          END;
CREATE TRIGGER trg_datarecord_balance_num_ins
          AFTER INSERT ON datarecord
          BEGIN
            UPDATE datarecord SET outstanding_balance_num = CASE
              WHEN NEW.outstanding_balance IS NULL OR NEW.outstanding_balance = '' OR NEW.outstanding_balance = '0'
                THEN NULL
              ELSE CAST(REPLACE(REPLACE(NEW.outstanding_balance, ',', ''), ' ', '') AS REAL)
            END WHERE id = NEW.id;
          END;
CREATE TRIGGER trg_datarecord_balance_num_upd
          AFTER UPDATE OF outstanding_balance ON datarecord
          BEGIN
            UPDATE datarecord SET outstanding_balance_num = CASE
              WHEN NEW.outstanding_balance IS NULL OR NEW.outstanding_balance = '' OR NEW.outstanding_balance = '0'
                THEN NULL
              ELSE CAST(REPLACE(REPLACE(NEW.outstanding_balance, ',', ''), ' ', '') AS REAL)
            END WHERE id = NEW.id;
          END;

-- ── depot_profile ──
CREATE TABLE depot_profile (
            id INTEGER PRIMARY KEY CHECK (id = 1),
            name TEXT,
            address_line1 TEXT,
            address_line2 TEXT,
            city TEXT,
            postal_code TEXT,
            phone TEXT,
            email TEXT,
            vat_number TEXT,
            registration_number TEXT,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
          );

-- ── error_log ──
CREATE TABLE error_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            source TEXT NOT NULL,
            level TEXT NOT NULL DEFAULT 'error',
            message TEXT NOT NULL,
            stack TEXT,
            context TEXT,
            occurred_at TEXT NOT NULL DEFAULT (datetime('now'))
          );
CREATE INDEX idx_error_log_level ON error_log(level, occurred_at DESC);
CREATE INDEX idx_error_log_occurred ON error_log(occurred_at DESC);
CREATE INDEX idx_error_log_source ON error_log(source, occurred_at DESC);

-- ── flag_snapshots ──
CREATE TABLE flag_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_number TEXT NOT NULL,
            source_table TEXT,
            flag_color TEXT,
            flag_reason TEXT,
            flag_created_by TEXT,
            flag_source TEXT,
            auto_flagged INTEGER DEFAULT 0,
            note TEXT,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
          );
CREATE INDEX idx_flag_snapshots_customer ON flag_snapshots (customer_number, source_table);

-- ── hub_backup_integrity ──
CREATE TABLE hub_backup_integrity (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            site_id TEXT,
            filename TEXT,
            result TEXT,
            checked_at TEXT DEFAULT (datetime('now'))
          );

-- ── hub_bat_summary ──
CREATE TABLE hub_bat_summary (
            site_id TEXT PRIMARY KEY,
            total_supplier REAL DEFAULT 0,
            total_sage REAL DEFAULT 0,
            total_variance REAL DEFAULT 0,
            weeks_count INTEGER DEFAULT 0,
            matched_count INTEGER DEFAULT 0,
            mismatch_count INTEGER DEFAULT 0,
            awaiting_count INTEGER DEFAULT 0,
            total_exceptions INTEGER DEFAULT 0,
            total_exception_amount REAL DEFAULT 0,
            last_upload_at TEXT,
            synced_at TEXT,
            last_error TEXT
          , missing_weeks_count INTEGER DEFAULT 0, last_paid_week INTEGER, last_paid_year INTEGER, last_bat_week INTEGER, last_bat_year INTEGER, missing_credit_notes_weeks TEXT, mismatch_weeks TEXT, summary_year INTEGER);
CREATE INDEX idx_hub_bat_summary_synced ON hub_bat_summary(synced_at);

-- ── hub_jti_archive ──
CREATE TABLE hub_jti_archive (
            id INTEGER PRIMARY KEY AUTOINCREMENT,

            -- Which site this came from (matches HUB_SITES.id)
            site_id        TEXT NOT NULL,
            site_archive_id INTEGER,

            -- Calendar month
            period_year    INTEGER NOT NULL,
            period_month   INTEGER NOT NULL CHECK (period_month BETWEEN 1 AND 12),

            -- Provenance copied from the site row
            generated_at   TEXT NOT NULL,
            generated_by   TEXT,
            source         TEXT NOT NULL CHECK (source IN ('scheduled', 'manual')),

            -- File on hub disk
            filename       TEXT NOT NULL,
            file_path      TEXT NOT NULL,
            byte_size      INTEGER NOT NULL,
            sha256         TEXT NOT NULL,
            row_count      INTEGER NOT NULL,

            -- Snapshot of label fields the site stamped in
            town_city      TEXT,
            region         TEXT,
            country        TEXT,
            site_label     TEXT,

            -- How / when the hub got the file
            received_at    TEXT NOT NULL DEFAULT (datetime('now')),
            received_via   TEXT NOT NULL CHECK (received_via IN ('push', 'pull'))
          );
CREATE UNIQUE INDEX idx_hub_jti_archive_dedup
          ON hub_jti_archive(site_id, sha256);
CREATE INDEX idx_hub_jti_archive_period
          ON hub_jti_archive(period_year DESC, period_month DESC, received_at DESC);
CREATE INDEX idx_hub_jti_archive_site
          ON hub_jti_archive(site_id, period_year DESC, period_month DESC);

-- ── hub_settings ──
CREATE TABLE hub_settings (
            key TEXT PRIMARY KEY,
            value TEXT
          );

-- ── hub_site_ping ──
CREATE TABLE hub_site_ping (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            site_slug TEXT NOT NULL,
            timestamp TEXT NOT NULL,
            online INTEGER NOT NULL DEFAULT 0,
            latency_ms INTEGER,
            created_at TEXT DEFAULT (datetime('now'))
          );

-- ── hub_user_sites ──
CREATE TABLE hub_user_sites (
            email TEXT NOT NULL,
            site_slug TEXT NOT NULL,
            pushed_at TEXT DEFAULT (datetime('now')),
            PRIMARY KEY (email, site_slug)
          );

-- ── inventory_forecast ──
CREATE TABLE inventory_forecast (
            item_number         TEXT PRIMARY KEY,
            avg_daily_demand    REAL,
            demand_std_dev      REAL,
            weighted_avg_3m     REAL,
            weighted_avg_6m     REAL,
            seasonality_index   REAL DEFAULT 1.0,
            adjusted_demand     REAL,
            safety_stock        REAL,
            reorder_point       REAL,
            days_of_stock       REAL,
            suggested_order_qty REAL,
            abc_class           TEXT,
            computed_at         TEXT
          );

-- ── inventory_forecast_config ──
CREATE TABLE inventory_forecast_config (
            item_number      TEXT PRIMARY KEY DEFAULT '__global__',
            lead_time_days   INTEGER DEFAULT 7,
            order_cycle_days INTEGER DEFAULT 14,
            service_level    REAL DEFAULT 0.95,
            min_order_qty    REAL DEFAULT 0
          );

-- ── inventory_sales_cache ──
CREATE TABLE inventory_sales_cache (
            item_number   TEXT    NOT NULL,
            period        TEXT    NOT NULL,
            qty_sold      REAL    NOT NULL DEFAULT 0,
            revenue       REAL    NOT NULL DEFAULT 0,
            order_count   INTEGER NOT NULL DEFAULT 0,
            last_sale_date TEXT,
            PRIMARY KEY (item_number, period)
          );
CREATE INDEX idx_inv_sales_item
            ON inventory_sales_cache(item_number);
CREATE INDEX idx_inv_sales_period
            ON inventory_sales_cache(period);

-- ── inventory_sales_sync_meta ──
CREATE TABLE inventory_sales_sync_meta (
            id    INTEGER PRIMARY KEY CHECK (id = 1),
            last_synced_at TEXT,
            last_synced_to TEXT,
            rows_synced    INTEGER DEFAULT 0
          );

-- ── inventory_sales_transactions ──
CREATE TABLE inventory_sales_transactions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            item_number      TEXT NOT NULL,
            transaction_date TEXT NOT NULL,
            order_number     TEXT,
            customer_code    TEXT,
            customer_name    TEXT,
            qty_sold         REAL NOT NULL DEFAULT 0,
            unit_price       REAL,
            line_amount      REAL,
            synced_at        TEXT DEFAULT CURRENT_TIMESTAMP
          );
CREATE INDEX idx_inv_txn_customer
            ON inventory_sales_transactions(customer_code);
CREATE INDEX idx_inv_txn_date
            ON inventory_sales_transactions(transaction_date);
CREATE INDEX idx_inv_txn_item_date
            ON inventory_sales_transactions(item_number, transaction_date);

-- ── inventoryrecord ──
CREATE TABLE "inventoryrecord" (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              source_table TEXT NOT NULL,
              item_number TEXT NOT NULL,
              item_description TEXT,
              qty_on_hand TEXT,
              last_cost TEXT,
              price_list TEXT,
              price TEXT,
              stocking_uom TEXT,
              commodity TEXT,
              inventory_value TEXT,
              terms TEXT,
              created_date TEXT DEFAULT CURRENT_TIMESTAMP,
              updated_date TEXT DEFAULT CURRENT_TIMESTAMP,
              UNIQUE(source_table, item_number)
            );
CREATE INDEX idx_inventoryrecord_source ON inventoryrecord (source_table, item_number);

-- ── job_runs ──
CREATE TABLE job_runs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            status TEXT NOT NULL CHECK (status IN ('started','succeeded','failed')),
            started_at TEXT NOT NULL,
            ended_at TEXT,
            duration_ms INTEGER,
            error_message TEXT,
            context TEXT
          );
CREATE INDEX idx_job_runs_name_started ON job_runs(name, started_at DESC);
CREATE INDEX idx_job_runs_started ON job_runs(started_at DESC);

-- ── jti_archive ──
CREATE TABLE jti_archive (
            id INTEGER PRIMARY KEY AUTOINCREMENT,

            -- Calendar month this export covers
            period_year   INTEGER NOT NULL,
            period_month  INTEGER NOT NULL CHECK (period_month BETWEEN 1 AND 12),

            -- Provenance
            generated_at  TEXT NOT NULL DEFAULT (datetime('now')),
            generated_by  TEXT,
            source        TEXT NOT NULL CHECK (source IN ('scheduled', 'manual')),

            -- File on disk
            filename      TEXT NOT NULL,
            file_path     TEXT NOT NULL,
            byte_size     INTEGER NOT NULL,
            sha256        TEXT NOT NULL,
            row_count     INTEGER NOT NULL,

            -- Snapshot of the address fields stamped into this archive,
            -- so a future "what label values did we use for April?"
            -- can be answered without re-reading the .xlsx.
            town_city     TEXT,
            region        TEXT,
            country       TEXT,
            site_label    TEXT,

            -- Hub push state machine (see migration comment)
            hub_push_status   TEXT NOT NULL DEFAULT 'pending'
              CHECK (hub_push_status IN ('pending', 'pushed', 'failed', 'skipped_no_hub')),
            hub_push_at       TEXT,
            hub_push_error    TEXT,
            hub_push_attempts INTEGER NOT NULL DEFAULT 0
          );
CREATE INDEX idx_jti_archive_hub_push
          ON jti_archive(hub_push_status);
CREATE INDEX idx_jti_archive_period
          ON jti_archive(period_year DESC, period_month DESC, generated_at DESC);

-- ── jti_settings ──
CREATE TABLE jti_settings (
            key TEXT PRIMARY KEY,
            value TEXT,
            updated_at TEXT DEFAULT (datetime('now'))
          );

-- ── login_log ──
CREATE TABLE login_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_email TEXT NOT NULL,
      user_name TEXT,
      ip_address TEXT,
      logged_in_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
CREATE INDEX idx_login_log_logged_in_at ON login_log(logged_in_at);

-- ── price_list_exclusions ──
CREATE TABLE price_list_exclusions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            pattern TEXT NOT NULL UNIQUE,
            note TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT
          );

-- ── schema_migrations ──
CREATE TABLE schema_migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      version INTEGER NOT NULL UNIQUE,
      name TEXT NOT NULL,
      applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- ── stock_receipt ──
CREATE TABLE stock_receipt (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            site_id TEXT NOT NULL DEFAULT '',
            source_table TEXT NOT NULL,
            receipt_number TEXT NOT NULL,
            supplier_code TEXT,
            supplier_name TEXT,
            receipt_date TEXT,
            external_uid TEXT,
            imported_at TEXT DEFAULT CURRENT_TIMESTAMP,
            created_date TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_date TEXT DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(site_id, source_table, receipt_number)
          );
CREATE INDEX idx_stock_receipt_date ON stock_receipt(receipt_date);
CREATE INDEX idx_stock_receipt_number ON stock_receipt(receipt_number);

-- ── stock_receipt_line ──
CREATE TABLE stock_receipt_line (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            receipt_id INTEGER NOT NULL REFERENCES stock_receipt(id) ON DELETE CASCADE,
            line_no INTEGER,
            item_number TEXT NOT NULL,
            item_description TEXT,
            qty_received TEXT,
            uom TEXT,
            unit_cost TEXT,
            batch_or_lot TEXT,
            source_line_uid TEXT,
            created_date TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_date TEXT DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(receipt_id, line_no, item_number)
          );
CREATE INDEX idx_stock_receipt_line_item ON stock_receipt_line(item_number);
CREATE INDEX idx_stock_receipt_line_receipt ON stock_receipt_line(receipt_id);

-- ── stock_receipt_line_expiry ──
CREATE TABLE stock_receipt_line_expiry (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            receipt_line_id INTEGER NOT NULL REFERENCES stock_receipt_line(id) ON DELETE CASCADE,
            expiry_date TEXT NOT NULL,
            qty_at_expiry TEXT,
            entered_by TEXT,
            entry_source TEXT DEFAULT 'manual',
            notes TEXT,
            created_date TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_date TEXT DEFAULT CURRENT_TIMESTAMP
          );
CREATE INDEX idx_stock_receipt_expiry_date ON stock_receipt_line_expiry(expiry_date);
CREATE INDEX idx_stock_receipt_expiry_line ON stock_receipt_line_expiry(receipt_line_id);

-- ── syncrun ──
CREATE TABLE syncrun (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      connection_id INTEGER NOT NULL,
      started_at TEXT NOT NULL,
      completed_at TEXT,
      status TEXT CHECK(status IN ('running', 'completed', 'failed', 'abandoned')) NOT NULL,
      message TEXT
    );
CREATE INDEX idx_syncrun_connection_id ON syncrun(connection_id);

-- ── user ──
CREATE TABLE "user" (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      email TEXT NOT NULL UNIQUE,
      full_name TEXT,
      created_date TEXT DEFAULT CURRENT_TIMESTAMP,
      role TEXT CHECK(role IN ('admin', 'user')) DEFAULT 'user',
      theme_preference TEXT CHECK(theme_preference IN ('light', 'dark')) DEFAULT 'light'
    , password_hash TEXT, must_change_password INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, can_access_customer_search INTEGER DEFAULT 1, can_access_records INTEGER DEFAULT 0, can_access_reports INTEGER DEFAULT 0, can_access_connections INTEGER DEFAULT 0, can_access_settings INTEGER DEFAULT 0, can_manage_users INTEGER DEFAULT 0, can_manage_rules INTEGER DEFAULT 0, can_edit_records INTEGER DEFAULT 1, can_flag_records INTEGER DEFAULT 1, hub_redirect INTEGER DEFAULT 0, can_access_customer_balances INTEGER DEFAULT 1, can_access_inventory INTEGER DEFAULT 1, can_access_collections INTEGER DEFAULT 1, can_access_hub_metrics INTEGER DEFAULT 0, can_access_hub_backups INTEGER DEFAULT 0, can_access_hub_trends INTEGER DEFAULT 0, can_access_hub_audit_log INTEGER DEFAULT 0, can_access_network_devices INTEGER DEFAULT 0, can_access_reconciliation INTEGER DEFAULT 0, can_access_hub_reconciliation INTEGER DEFAULT 0, can_access_jti INTEGER DEFAULT 0, can_access_stock_receipt_expiry INTEGER DEFAULT 0, can_access_inventory_movement INTEGER DEFAULT 0, can_access_price_list INTEGER DEFAULT 0);
